name: 'Check Application'
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Execute composite
        uses: ./.github/actions/
      - name: 'Run Lint'
        run: pnpm run lint

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Execute composite
        uses: ./.github/actions/
      - name: 'Run tests'
        run: pnpm vitest
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Execute composite
        uses: ./.github/actions/
      - name: Run coverage for SonarCloud
        run: pnpm test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
