name: 'Check Application'
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Execute composite
        uses: ./.github/actions/
      - name: 'Run Lint'
        run: pnpm run lint

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Execute composite
        uses: ./.github/actions/action.yaml
      - name: 'Run tests'
        run: pnpm vitest
